services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "18001:18001"
    volumes:
      - .:/app
    networks:
      - mynetwork

  pytorch:
    build:
      context: .
      dockerfile: Dockerfile.pytorch
    ports:
      - "18002:18002"
    networks:
      - mynetwork

networks:
  mynetwork:
    