version: "3.9"
services:
  holic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: holic
    ports:
      - "18001:18001"
    volumes:
      - holic_data:/holic
volumes:
  holic_data: